### ISSUE TITLE
New iOS App forgetting gke clusters on relaunch

### ISSUE THREAD

**Issue by GEverding** [bitnami-labs/cabin#76]
Hi,

Updated to the latest version of cabin on iOS and when I add a new gke cluster and close the app is forgets about it next time I open the app. Reinstalled the app and same behaviour.

**Comment by amazaheri** [comment]
+1

**Comment by 6869dan** [comment]
Same here. Was previously working for the same gke cluster but now when I add it, all the resources show as down (they're not) and when I relaunch Cabin shows no saved clusters. Tried reinstalling.

**Comment by sudermanjr** [comment]
Having the same issue with non-GKE clusters on iOS

**Comment by amazaheri** [comment]
I hope folks monitoring the thread here

**Comment by jbelinchonm** [comment]
+1

**Comment by camilb** [comment]
Same here. Tested on 3 devices (iPhone 6, 7 and iPad Pro)

**Comment by vistalba** [comment]
Same here with two different non-GCE Clusters on iOS11.2.
Any news about this bug?
(If I add the Cluster again, all works fine).

**Comment by orsh** [comment]
+1

**Comment by JimBledsoe** [comment]
+1 on IOS with GKE

**Comment by paolomainardi** [comment]
Same here, are there any planned fixes?

**Comment by zihzo** [comment]
Same here any fixes planned ?

**Comment by ArchiFleKs** [comment]
+1 custom cluster with p12 certificate is forgotten each time the app is closed

**Comment by paolomainardi** [comment]
Any chances to get this bug fixed ?

**Comment by thetechnick** [comment]
Same bug with custom clusters on Android 6.0, enabling/disabling of resource types in the app settings seems to be affected as well.

**Comment by chapati23** [comment]
Still an issue. Any pointer from maintainers on how to fix would be awesome so the community can step in and help out

**Comment by paolomainardi** [comment]
I think that this project is abandoned

**Comment by chapati23** [comment]
well, it's open source . so it's only abandoned if all of us decide it's abandoned.

@sebgoa / @kemcake any pointers on how to fix this so somebody else can take a stab at it if you're too busy?

no hard feelings, i know you're not getting paid for supporting this, but it's a really cool app and would be a shame letting it go to waste

**Comment by kemcake** [comment]
Alright, seems like no ones maintaining that after I left, sorry about that guys, looks like a really bad issue, I'll take look today at it really soon and see what I can do... 🧐

**Comment by kemcake** [comment]
Alright guys, issue identified, simply forgot to add initializeApplication action call back when removing Application component.
--> https://github.com/bitnami-labs/cabin/pull/73/files#diff-ea1d824129ad4618571a8f9b2bbc44f9L39

I'm gonna see how soon bitnami can publish the update on app stores.

Once again sorry about that, weird that I missed a so obvious bug. At least this made me realise that people care about this app :) 

(I'll close the issue when apps are released)

**Comment by kemcake** [comment]
Update: Android update is live. iOS be a bit longer (few days) as always

**Comment by chapati23** [comment]
Thanks a lot @kemcake!

**Comment by 6869dan** [comment]
Thanks! \o/ Will update and test, great app, really pleased with the
functionality in gke.

**Comment by sebgoa** [comment]
@kemcake thanks for staying on top of it.

**Comment by sebgoa** [comment]
@paolomainardi the project is not abandoned, we just trying to figure out how to move forward. @kemcake moved on to a new job.

We will gladly accept PRs to fix problems, but we also have other priorities and could not fix this quickly. Sorry about that.

**Comment by paolomainardi** [comment]
Thanks a lot @kemcake and @sebgoa for the updates, very much appreciated.

**Comment by sebgoa** [comment]
If users of that app where to come out in force , we could make a case to the kubernetes leadership to get it inside the incubator.

It might help with maintenance.

**Comment by mnwalker** [comment]
Has anyone tested the 0.4.2 android release?
Even after the update I am experiencing this same issue.

Moving app into the background keeps the cluster config saved, but pressing back until it closes or closing from app switcher and config is gone.
Android on S6 edge

**Comment by alexmg** [comment]
I also have the same issues after updating on Android. Config is not saved and cluster is shown as not running when it actually is. Would be nice to see some logs somewhere to help debug issues.

**Comment by chapati23** [comment]
Is the iOS app still pending AppStore approval?

**Comment by sebgoa** [comment]
cc/ @bhullnatik that's one of the issues

**Comment by ashanaakh** [comment]
+1

**Comment by vistalba** [comment]
No update on iOS AppStore until today. Any news about this issue?

**Comment by sebgoa** [comment]
We are working on a fix cc/ @bhullnatik I swear :)

**Comment by Bhullnatik** [comment]
Hey everyone,

We just released version 0.5.0 that should fix this issue for good.
Please update your app, and let us know if it works (but it should)!

Thank you for your patience and your help.

**Comment by amazaheri** [comment]
I see the same issue as https://github.com/bitnami-labs/cabin/issues/75 after upgrading to 0.5.0

**Comment by jbelinchonm** [comment]
Works perfect!
Good Job!
iOS 11.3.1 iPhone 6
iOS latest iPad2
