### ISSUE TITLE
X509 Certificate Authority blocked on android

### ISSUE THREAD

**Issue by thetechnick** [bitnami-labs/cabin#79]
When adding a custom kubernetes cluster with self signed certificates under Android, the cluster will be shown as "down" (I guess the self signed certificate is rejected by the http client). While on iOS the cluster is working as expected and is shown as "running".

My current workaround is to re-terminate the TLS connection to the k8s API using nginx and a lets encrypt certificate.

Thanks for the great app, its really cool to lookup your cluster`s workload on mobile devices :)

**Comment by Bhullnatik** [comment]
Hey,

We just released version 0.5.0 that should fix your issue. 
Please update your app, and let us know if it works!
