### ISSUE TITLE
Custer config not saved

### ISSUE THREAD

**Issue by mnwalker** [bitnami-labs/cabin#80]
Been struggling to get cabin to work properly, first issue was self signed certificate on the api which I solved by putting behind cloudflare.

Now I can enter cluster details and connect, but every time I close the app my cluster is gone and I have to enter all config details again.

Android app version 0.4.1 on an S6 edge

**Comment by rickard-von-essen** [comment]
Duplicates #76

**Comment by kemcake** [comment]
Closing, duplicate of #76 . which is fixed btw
